from SoupFactory import SoupFactory  
from SoupGameweek import GameweekSoup
from SoupLeague import LeagueSoup
from SoupMatchDetails import MatchDetailsSoup
from SoupMatchEvents import MatchEventsSoup
from SoupMatchEventsHeading import MatchEventsHeadingSoup
from SoupMatchHeading import MatchHeadingSoup
# from SoupPlayerDetails import PlayerDetailsSoup
from SoupPlayerHeading import PlayerHeadingSoup
from SoupRegion import RegionSoup
from SoupSquads import SquadsSoup